client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
    shortname = localhost
}
client localhost_ipv6 {
    ipv6addr = ::1
    secret = testing123
    shortname = localhost-v6
}
client docker-network {
    ipaddr = 172.30.0.0/24
    secret = nac_internal_secret
    shortname = docker-internal
}
client policy-engine {
    ipaddr = 172.30.0.20
    secret = changeme_coa_secret
    shortname = policy-engine
}
